name: A Broken Sky
favicon: null
layout_spectrum: 0.8493085273075849
typography_spectrum: 0.2162652078550309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4522674104664475
  lightness: 0.22164668515324593
  saturation: 0.18384324945509434
  rhythmicContrast: 0.6581550270784646
purpose: []
